INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (2, '2.png', 'image/png', 'C:/login/2.png', 2);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (5, '파자마_잠옷_채팅.png', 'image/png', 'C:/login/파자마_잠옷_채팅.png', 15);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (7, 'hooni.jpg', 'image/jpeg', 'C:/login/hooni.jpg', 25);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (8, '2.png', 'image/png', 'C:/login/2.png', 29);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (9, '6.gif', 'image/gif', 'C:/login/6.gif', 29);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (10, 'KakaoTalk_20230625_221341626.jpg', 'image/jpeg', 'C:/login/KakaoTalk_20230625_221341626.jpg', 29);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (11, '2.png', 'image/png', 'C:/login/2.png', 30);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (12, '6.gif', 'image/gif', 'C:/login/6.gif', 30);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (13, 'KakaoTalk_20230625_221341626.jpg', 'image/jpeg', 'C:/login/KakaoTalk_20230625_221341626.jpg', 30);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (14, '6.gif', 'image/gif', 'C:/login/6.gif', 31);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (15, 'KakaoTalk_20230625_221341626.jpg', 'image/jpeg', 'C:/login/KakaoTalk_20230625_221341626.jpg', 31);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (16, 'test.txt', 'text/plain', 'C:/login/test.txt', 30);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (17, 'jjang-gu.png', 'image/png', 'C:/login/jjang-gu.png', 122);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (18, 'test.txt', 'text/plain', 'C:/login/test.txt', 30);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (19, 'jjang-gu.png', 'image/png', 'C:/login/jjang-gu.png', 123);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (20, 'favicon.ico', 'image/x-icon', 'C:/login/favicon.ico', 124);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (21, 'favicon.ico', 'image/x-icon', 'C:/login/favicon.ico', 134);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (22, 'favicon.ico', 'image/x-icon', 'C:/login/favicon.ico', 135);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (23, '### 포트폴리오.txt', 'text/plain', 'C:/login/### 포트폴리오.txt', 136);
INSERT INTO insider.announce_files (FILE_NO, FILE_NAME, FILE_TYPE, FILE_PATH, ANC_NO) VALUES (24, '#1 공지사항 등록.txt', 'text/plain', 'C:/login/#1 공지사항 등록.txt', 136);
