INSERT INTO insider.department_info (depart_no, depart_name) VALUES (1, '인사팀');
INSERT INTO insider.department_info (depart_no, depart_name) VALUES (2, '개발팀');
INSERT INTO insider.department_info (depart_no, depart_name) VALUES (3, '영업팀');
INSERT INTO insider.department_info (depart_no, depart_name) VALUES (4, '품질관리팀');
INSERT INTO insider.department_info (depart_no, depart_name) VALUES (16, '총무팀');
INSERT INTO insider.department_info (depart_no, depart_name) VALUES (17, '기획팀');
INSERT INTO insider.department_info (depart_no, depart_name) VALUES (18, '회계팀');
INSERT INTO insider.department_info (depart_no, depart_name) VALUES (19, '운영팀');
INSERT INTO insider.department_info (depart_no, depart_name) VALUES (20, '재무팀');
