INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (7, '7/5 금', 1, 3);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (8, '7/12 금', 2, 3);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (9, '7/20 금', 3, 3);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (10, 'ㄴㅇㅇㄴㄴㅇㅇㄴ', 1, 4);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (11, 'ㅊㅍㅍㅊㅍㅊㅍㅊ', 1, 5);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (12, 'ㅊㅍㅍㅊㅊㅍㅊㅍ', 2, 5);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (13, 'ㅌㅋㅌㅊㅌㅋ', 1, 6);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (14, 'ㅌㅊㅊㅌㅌㅊ', 1, 7);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (15, '1. 6월 30일', 1, 8);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (16, '2. 7월 5일', 2, 8);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (17, '3. 7월 8일', 3, 8);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (18, 'ㅇㅋ', 1, 9);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (19, '123', 1, 10);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (20, '7월 1일', 1, 11);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (21, '7월 2일', 2, 11);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (22, '7월 3일', 3, 11);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (23, '몽쉘', 1, 12);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (24, '오예스', 2, 12);
INSERT INTO insider.survey_answer (answer_no, answer, answer_sequence, survey_no) VALUES (25, '초코파이', 3, 12);
